server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/users/**

        - id: appointment-service
          uri: ${APPOINTMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/appointments/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/notifications/**

        - id: ai-service
          uri: ${AI_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/ai/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

eureka:
  client:
    enabled: false

logging:
  level:
    com.mediconnect: INFO
