server:
  port: 8085

spring:
  application:
    name: ai-service
  main:
    web-application-type: servlet
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

gemini:
  api:
    key: AIzaSyBPUSOEku7HCW_obwThFw0IlidyTPYUxBM
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.mediconnect: DEBUG